eureka:
  instance:
    instance-id: 'user-1'
    lease-renewal-interval-in-seconds: 1      # 发送心跳的时间
    lease-expiration-duration-in-seconds: 3   # 多久不发送心跳就移除
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka
#    enabled: false
#    fetch-registry: false
spring:
  application:
    name: 'user'
  zipkin: 
    base-url: http://localhost:5000  #指定Zipkin server地址 
  sleuth: 
    sampler: 
      probability: 1.0
hystrix:
  command:
    # 是指power实例的配置时间
    default:
      circuitBreaker:
        enable: true
        requestVolumeThreshold: 10         # 同时有5个请求失败就执行短路操作
        sleepWindowInMilliseconds: 10000  # 失败请求的时间区间
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 设置hystrix的超时时间为5000ms
  threadpool:
    default:
      coresize: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8999
    

