server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: zuul-1
    prefer-ip-address: true
spring:
    application:
      name: zuul
zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    myPower:
      serviceId: power
      path: /power/**
    myUser:
      serviceId: user
      path: /user/**


